<?php

/**
 * Created by PhpStorm.
 * User: Nivanka Fonseka
 * Date: 06/10/2017
 * Time: 20:54
 */
class ChunkUploadField extends HiddenField
{

    public function Field($properties = array())
    {
        Requirements::javascript(THIRDPARTY_DIR . '/jquery/jquery.js');
        Requirements::javascript('chunkuploader/client/dist/bundle/common.min.js');
        Requirements::css('chunkuploader/client/dist/styles.min.css');
        return parent::Field($properties); // TODO: Change the autogenerated stub
    }

    public function getUploadTarget()
    {
        return Director::baseURL() . 'chunkupload/handle';
    }

}